### ISSUE TITLE
Incorrect test.yml configuration in Set up CI section

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix-docs#987]
There must not be additional "-" for steps after name. The correct configuration is:
```
steps:
  - name: Git Checkout
    uses: actions/checkout@v2

  - name: Set up JDK 17
    uses: actions/setup-java@v1
    with:
      java-version: '17'
```

Also for Windows users we can note that "gradlew" must be executable. For instance, we can add the following step before running tests:
```
- name: Make wrapper executable
  run: chmod +x ./gradlew
```
